#!/bin/bash
# This deletes all temp files generated by ColdVector This exists for testing
ls | grep -P "^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$" | xargs -d"\n"  rm
